server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://175.210.112.200:3006/mes_sgi?useSSL=false&serverTimezone=Asia/Seoul
    username: bizplus
    password: bizplus
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true

  #liveReload
  devtools:
    livereload:
      enabled: true